DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS profiles;

CREATE TABLE USERS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USERNAME TEXT UNIQUE NOT NULL,
	PASSWORD TEXT NOT NULL,
	ROLE TEXT CHECK(ROLE IN ("PATIENT", "PHYSICIAN", "ADMIN")) NOT NULL,
	VERIFIED BOOLEAN DEFAULT 0
);
CREATE TABLE PROFILES (
	USER_ID INTEGER PRIMARY KEY,
	NAME_FIRST TEXT,
	NAME_LAST TEXT,
	EMAIL TEXT,
	DOB DATE,
	PHONE TEXT,
	ADDRESS TEXT,
	FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);