DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USER_DETAILS;
DROP TABLE IF EXISTS PATIENTS;
DROP TABLE IF EXISTS APPOINTMENTS;

CREATE TABLE USERS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USERNAME TEXT UNIQUE NOT NULL,
	PASSWORD TEXT NOT NULL,
	ROLE TEXT NOT NULL CHECK (ROLE IN ("PHYSICIAN", "ADMIN"))
);

CREATE TABLE USER_DETAILS (
	USER_ID INTEGER PRIMARY KEY,
	NAME_FIRST TEXT,
	NAME_LAST TEXT,
	EMAIL TEXT,
	DOB DATE,
	PHONE TEXT,
	ADDRESS TEXT,
	FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE PATIENTS (
	ID INTEGER PRIMARY KEY,
	NAME_FIRST TEXT,
	NAME_LAST TEXT,
	EMAIL TEXT,
	DOB DATE,
	SEX TEXT,
	PHONE TEXT,
	ADDRESS TEXT
);

CREATE TABLE APPOINTMENTS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	PATIENT_ID INTEGER NOT NULL,
	PHYSICIAN_ID INTEGER NOT NULL,
	TIME DATE NOT NULL,
	STATUS TEXT NOT NULL,
	NOTES TEXT,
	CHECK (STATUS IN ("SCHEDULED", "IN PROGRESS", "COMPLETED", "MISSED"))
);